[versions]
kotlin = "2.3.0"
composeMultiplatform = "1.11.0-alpha01"

composeMaterial3 = "1.9.0"
kotlinxCollections = "0.4.0"

[plugins]
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
kotlinx-collections  = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollections" }

jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "composeMultiplatform" }
jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "composeMultiplatform" }
jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "composeMultiplatform" }
jetbrains-compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "composeMaterial3" }

[bundles]
jetbrains-compose = [
    "jetbrains-compose-foundation",
    "jetbrains-compose-runtime",
    "jetbrains-compose-ui",
    "jetbrains-compose-material3"
]